settings:
  title: 'Status Page'
  url: 'https://status-page.eidam.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: workers-cloudflare-com # unique identifier
    name: ChatGPT拼车小队
    description: 'You write code. They handle the rest.' # default=empty
    url: 'https://52cuc.lol/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

  - id: www-cloudflare-com
    name: ChatGPT官网
    description: 'Built for anything connected to the Internet.'
    url: 'https://www.chatgpt.com'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: blog-cloudflare-com
    name: 网关
    url: 'https://chat.oaifree.com/dad04481-fa3f-494e-b90c-b822128073e5'
    method: GET
    expectStatus: 200
